package com.ams.modelo.gestion_usuario;
// Generated 10-02-2014 02:11:14 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Menus generated by hbm2java
 */
@Entity
@Table(name="menus"
    , uniqueConstraints = @UniqueConstraint(columnNames="nombre") 
)
public class Menus  implements java.io.Serializable {


     private int id;
     private Menus menus;
     private String nombre;
     private Integer orden;
     private Boolean pasivo;
     private Date creadoEl;
     private Date modificadoEl;
     private Integer creadoPor;
     private Integer modificadoPor;
     private String creadoEnIp;
     private String modificadoEnIp;
     private String codigo;
     private Set menuses = new HashSet(0);
     private Set rolesMenuses = new HashSet(0);

    public Menus() {
    }

	
    public Menus(int id, String nombre, String codigo) {
        this.id = id;
        this.nombre = nombre;
        this.codigo = codigo;
    }
    public Menus(int id, Menus menus, String nombre, Integer orden, Boolean pasivo, Date creadoEl, Date modificadoEl, Integer creadoPor, Integer modificadoPor, String creadoEnIp, String modificadoEnIp, String codigo, Set menuses, Set rolesMenuses) {
       this.id = id;
       this.menus = menus;
       this.nombre = nombre;
       this.orden = orden;
       this.pasivo = pasivo;
       this.creadoEl = creadoEl;
       this.modificadoEl = modificadoEl;
       this.creadoPor = creadoPor;
       this.modificadoPor = modificadoPor;
       this.creadoEnIp = creadoEnIp;
       this.modificadoEnIp = modificadoEnIp;
       this.codigo = codigo;
       this.menuses = menuses;
       this.rolesMenuses = rolesMenuses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="menu_id")
    public Menus getMenus() {
        return this.menus;
    }
    
    public void setMenus(Menus menus) {
        this.menus = menus;
    }

    
    @Column(name="nombre", unique=true, nullable=false, length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="orden")
    public Integer getOrden() {
        return this.orden;
    }
    
    public void setOrden(Integer orden) {
        this.orden = orden;
    }

    
    @Column(name="pasivo")
    public Boolean getPasivo() {
        return this.pasivo;
    }
    
    public void setPasivo(Boolean pasivo) {
        this.pasivo = pasivo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creado_el", length=29)
    public Date getCreadoEl() {
        return this.creadoEl;
    }
    
    public void setCreadoEl(Date creadoEl) {
        this.creadoEl = creadoEl;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modificado_el", length=29)
    public Date getModificadoEl() {
        return this.modificadoEl;
    }
    
    public void setModificadoEl(Date modificadoEl) {
        this.modificadoEl = modificadoEl;
    }

    
    @Column(name="creado_por")
    public Integer getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(Integer creadoPor) {
        this.creadoPor = creadoPor;
    }

    
    @Column(name="modificado_por")
    public Integer getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(Integer modificadoPor) {
        this.modificadoPor = modificadoPor;
    }

    
    @Column(name="creado_en_ip", length=20)
    public String getCreadoEnIp() {
        return this.creadoEnIp;
    }
    
    public void setCreadoEnIp(String creadoEnIp) {
        this.creadoEnIp = creadoEnIp;
    }

    
    @Column(name="modificado_en_ip", length=20)
    public String getModificadoEnIp() {
        return this.modificadoEnIp;
    }
    
    public void setModificadoEnIp(String modificadoEnIp) {
        this.modificadoEnIp = modificadoEnIp;
    }

    
    @Column(name="codigo", nullable=false)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="menus")
    public Set getMenuses() {
        return this.menuses;
    }
    
    public void setMenuses(Set menuses) {
        this.menuses = menuses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="menus")
    public Set getRolesMenuses() {
        return this.rolesMenuses;
    }
    
    public void setRolesMenuses(Set rolesMenuses) {
        this.rolesMenuses = rolesMenuses;
    }




}


