package com.ams.modelo.gestion_usuario;
// Generated 10-02-2014 02:11:14 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="usuarios"
    , uniqueConstraints = {@UniqueConstraint(columnNames="email"), @UniqueConstraint(columnNames="reset_password_token"), @UniqueConstraint(columnNames="user_name")} 
)
public class Usuarios  implements java.io.Serializable {


     private int id;
     private String userName;
     private String userPassword;
     private String nombre1;
     private String nombre2;
     private String apellido1;
     private String apellido2;
     private boolean pasivo;
     private String email;
     private String encryptedPassword;
     private String resetPasswordToken;
     private Integer failedAttempts;
     private String unlockToken;
     private Date lockedAt;
     private String referencia;
     private Integer creadoPor;
     private Integer modificadoPor;
     private Date creadoEl;
     private Date modificadoEl;
     private String creadoEnIp;
     private String modificadoEnIp;
     private Set permisoses = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(int id, String userName, String userPassword, String nombre1, String nombre2, String apellido1, String apellido2, boolean pasivo, String email, String encryptedPassword) {
        this.id = id;
        this.userName = userName;
        this.userPassword = userPassword;
        this.nombre1 = nombre1;
        this.nombre2 = nombre2;
        this.apellido1 = apellido1;
        this.apellido2 = apellido2;
        this.pasivo = pasivo;
        this.email = email;
        this.encryptedPassword = encryptedPassword;
    }
    public Usuarios(int id, String userName, String userPassword, String nombre1, String nombre2, String apellido1, String apellido2, boolean pasivo, String email, String encryptedPassword, String resetPasswordToken, Integer failedAttempts, String unlockToken, Date lockedAt, String referencia, Integer creadoPor, Integer modificadoPor, Date creadoEl, Date modificadoEl, String creadoEnIp, String modificadoEnIp, Set permisoses) {
       this.id = id;
       this.userName = userName;
       this.userPassword = userPassword;
       this.nombre1 = nombre1;
       this.nombre2 = nombre2;
       this.apellido1 = apellido1;
       this.apellido2 = apellido2;
       this.pasivo = pasivo;
       this.email = email;
       this.encryptedPassword = encryptedPassword;
       this.resetPasswordToken = resetPasswordToken;
       this.failedAttempts = failedAttempts;
       this.unlockToken = unlockToken;
       this.lockedAt = lockedAt;
       this.referencia = referencia;
       this.creadoPor = creadoPor;
       this.modificadoPor = modificadoPor;
       this.creadoEl = creadoEl;
       this.modificadoEl = modificadoEl;
       this.creadoEnIp = creadoEnIp;
       this.modificadoEnIp = modificadoEnIp;
       this.permisoses = permisoses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="user_name", unique=true, nullable=false, length=50)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="user_password", nullable=false, length=25)
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    
    @Column(name="nombre1", nullable=false, length=50)
    public String getNombre1() {
        return this.nombre1;
    }
    
    public void setNombre1(String nombre1) {
        this.nombre1 = nombre1;
    }

    
    @Column(name="nombre2", nullable=false, length=50)
    public String getNombre2() {
        return this.nombre2;
    }
    
    public void setNombre2(String nombre2) {
        this.nombre2 = nombre2;
    }

    
    @Column(name="apellido1", nullable=false, length=50)
    public String getApellido1() {
        return this.apellido1;
    }
    
    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }

    
    @Column(name="apellido2", nullable=false, length=50)
    public String getApellido2() {
        return this.apellido2;
    }
    
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }

    
    @Column(name="pasivo", nullable=false)
    public boolean isPasivo() {
        return this.pasivo;
    }
    
    public void setPasivo(boolean pasivo) {
        this.pasivo = pasivo;
    }

    
    @Column(name="email", unique=true, nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="encrypted_password", nullable=false)
    public String getEncryptedPassword() {
        return this.encryptedPassword;
    }
    
    public void setEncryptedPassword(String encryptedPassword) {
        this.encryptedPassword = encryptedPassword;
    }

    
    @Column(name="reset_password_token", unique=true)
    public String getResetPasswordToken() {
        return this.resetPasswordToken;
    }
    
    public void setResetPasswordToken(String resetPasswordToken) {
        this.resetPasswordToken = resetPasswordToken;
    }

    
    @Column(name="failed_attempts")
    public Integer getFailedAttempts() {
        return this.failedAttempts;
    }
    
    public void setFailedAttempts(Integer failedAttempts) {
        this.failedAttempts = failedAttempts;
    }

    
    @Column(name="unlock_token")
    public String getUnlockToken() {
        return this.unlockToken;
    }
    
    public void setUnlockToken(String unlockToken) {
        this.unlockToken = unlockToken;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="locked_at", length=29)
    public Date getLockedAt() {
        return this.lockedAt;
    }
    
    public void setLockedAt(Date lockedAt) {
        this.lockedAt = lockedAt;
    }

    
    @Column(name="referencia", length=200)
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }

    
    @Column(name="creado_por")
    public Integer getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(Integer creadoPor) {
        this.creadoPor = creadoPor;
    }

    
    @Column(name="modificado_por")
    public Integer getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(Integer modificadoPor) {
        this.modificadoPor = modificadoPor;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="creado_el", length=29)
    public Date getCreadoEl() {
        return this.creadoEl;
    }
    
    public void setCreadoEl(Date creadoEl) {
        this.creadoEl = creadoEl;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modificado_el", length=29)
    public Date getModificadoEl() {
        return this.modificadoEl;
    }
    
    public void setModificadoEl(Date modificadoEl) {
        this.modificadoEl = modificadoEl;
    }

    
    @Column(name="creado_en_ip", length=20)
    public String getCreadoEnIp() {
        return this.creadoEnIp;
    }
    
    public void setCreadoEnIp(String creadoEnIp) {
        this.creadoEnIp = creadoEnIp;
    }

    
    @Column(name="modificado_en_ip", length=20)
    public String getModificadoEnIp() {
        return this.modificadoEnIp;
    }
    
    public void setModificadoEnIp(String modificadoEnIp) {
        this.modificadoEnIp = modificadoEnIp;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuarios")
    public Set getPermisoses() {
        return this.permisoses;
    }
    
    public void setPermisoses(Set permisoses) {
        this.permisoses = permisoses;
    }




}


